name: Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      commit_sha:
        description: The commit SHA to deploy. When not passed, it deploys the latest commit available in `main`.
        required: false

concurrency:
  group: deploy-${{ github.head_ref }}
  cancel-in-progress: true

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
  MISE_EXPERIMENTAL: 1

jobs:
  production:
    environment:
      name: production
      url: https://rssletter.me
    name: Production
    env:
      FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
      DOCKER_BUILDKIT: 1
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4
        if: ${{ github.event.inputs.commit_sha == '' }}
      - uses: actions/checkout@v4
        if: ${{ github.event.inputs.commit_sha != '' }}
        with:
          ref: ${{ github.event.inputs.commit_sha }}
      - uses: jdx/mise-action@v2
      - name: 'Get version'
        id: version
        run: |
          version=$(.mise/tasks/generate-version)
          echo "::set-output name=version::$version"
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Fly
        run: flyctl deploy --remote-only -c fly.toml --build-arg MIX_ENV=prod --build-arg APP_REVISION=$GITHUB_SHA --wait-timeout 3600